### ISSUE TITLE
TextHandler Continually Overflows RAM with ~100K Lines of Text

### ISSUE THREAD

**Issue by AlexMRuch** [MilaNLProc/contextualized-topic-models#11]
* Contextualized Topic Models version: contextualized-topic-models 1.3.1
* Python version: Python 3.6.10
* Operating System: Ubuntu 18.04

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I have a .txt file with ~100,000 lines of text, all of which are between 30 and 128 words long. When I try to initialize `TextHandler` with this dataset and prepare the resulting handler object, the TextHandler pipeline quickly overflows my 128 GB of RAM.

I'm not sure if I'm running something incorrectly or if this method can only work with very small datasets. Hopefully it's not the latter, given that standard topic modeling and other BERT-based sentence encoding methods work fine on my server with far more data that are even longer (e.g., 512 words maximum) – and with much less RAM.

### What I Did

Here is how I initialized the TextHandler and prepared it:
```
handler = TextHandler("/media/seagate0/amazon/data/lang_pol_data_cult_bks_sampled_text.txt")
handler.prepare()
```

Halfway through the preparation, Python thew this warning, after which it overflowed the RAM and crashed:
```
/home/amruch/anaconda3/envs/nlp_polarization/lib/python3.6/site-packages/contextualized_topic_models/utils/data_preparation.py:62: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self.vocab_dict[x], y.split()))), data)))
```

Many thanks for any suggestions! Very much looking forward to applying this method!

**Comment by AlexMRuch** [comment]
Oh gosh, pretty sure the cause of this is me saving the text file wrong #facepalm. Will confirm tomorrow.

**Comment by silviatti** [comment]
Hello! 
That seems strange. Another user already tried to use the library here (#7) with over a million documents but didn't mention this kind of issue. 
Make sure that the format of the input file is like this one: [https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/data/sample_text_document](url)

Let me know if you solved it :)

Silvia

**Comment by AlexMRuch** [comment]
Yeah, I just confirmed that it still fails almost immediately even when I save the text file more properly, so it's not the saving part I mentioned. This time, however, it throws this error:
```
/home/amruch/anaconda3/envs/nlp_polarization/lib/python3.6/site-packages/contextualized_topic_models/utils/data_preparation.py:62: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self.vocab_dict[x], y.split()))), data)))
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/nlp_polarization/lib/python3.6/site-packages/contextualized_topic_models/utils/data_preparation.py in prepare(self)
     62                                                                       self.vocab_dict[x], y.split()))), data)))
     63         self.idx2token = {v: k for (k, v) in self.vocab_dict.items()}
---> 64         self.bow = get_bag_of_words(self.index_dd, len(self.vocab))
     65 
     66 

~/anaconda3/envs/nlp_polarization/lib/python3.6/site-packages/contextualized_topic_models/utils/data_preparation.py in get_bag_of_words(data, min_length)
      7     vect = [np.bincount(x[x != np.array(None)].astype('int'), minlength=min_length)
      8             for x in data if np.sum(x[x != np.array(None)]) != 0]
----> 9     return np.array(vect)
     10 
     11 

MemoryError: Unable to allocate 190. GiB for an array with shape (132124, 193109) and data type int64
```

Trying to figure out where the 193,109 is coming from for the columns number there. The 132,124 number is how many lines of text I have. Is this creating for each line a one-hot encoded vector for tokens? I presume so given the `bow` reference. If that's the case, sounds like I'll probably have to do more word removal in addition to the stopword removal and lemmatization I'm doing. That still seems odd to me, given what makes BERT so great is that you shouldn't have to do those things.

I'll check out the link you shared. Thanks so much, @silviatti

**Comment by silviatti** [comment]
I've just noticed that you are using version 1.3.1 of the package. From version 1.4.1 we are able to handle datasets with larger vocabularies. Updating your package will probably fix your issue :) 

As explained in #7, the BOW representation is necessary for our model and it allows us to extract the most relevant words for each topic. I suggest you preprocess the input text for the BOW, it will reduce the computational costs, and discarding the less frequent words may also lead to better results.  

Waiting for your feedback! 

Silvia

**Comment by AlexMRuch** [comment]
Wow-wow-wowwww, yeah, not only did that fix the problem but it also made the `TextHandler` `prepare` method run about 100 times faster. Thanks for the suggestion on that. I usually avoid upgrading packages in my environments unless there is a major development, and that was certainly a major development you all made. Thank you so much!
