### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by TudorAndrei** [MilaNLProc/contextualized-topic-models#113]
* Contextualized Topic Models version: 2.3.0
* Python version: 3.8.12
* Operating System: Ubuntu 22.04.1 LTS x86_64

### Description

I ran the ZeroShotTM example notebook on my local machine.

### What I Did

1.

```
topics_predictions = ctm.get_thetas(training_dataset, n_samples=5) # get all the topic predictions
```

```
DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
  if type(self.X_bow[i]) == scipy.sparse.csr.csr_matrix:
```

2.
```
import pyLDAvis as vis
movies_pd = vis.prepare(**lda_vis_data)
vis.display(movies_pd)
```
```
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _np_version_forbids_neg_powint = LooseVersion(numpy.__version__) >= LooseVersion('1.12.0b1')`
```

**Comment by vinid** [comment]
Hello @TudorAndrei !

Thanks, guess we should update our dependencies

**Comment by karanwanchoo** [comment]
I still get this error while using from contextualized_topic_models.models.kitty_classifier import Kitty

**Comment by Ton-moy** [comment]
I am also getting deprecation warnings.

"DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated."
