### ISSUE TITLE
How do I use a Kitty trained model with pyLDAvis?

### ISSUE THREAD

**Issue by marcmaxson** [MilaNLProc/contextualized-topic-models#116]
* Contextualized Topic Models version:
* Python version: 3.9
* Operating System: MacOS

### Description

I'd like to look at the results of my model, trained using Kitty, in pyLDAvis. 
It appears like one of the required inputs, `training_dataset` is not retained in the model, so I can't pass them into this function:

```
lda_vis_data = kt.ctm.get_ldavis_data_format(kt.qt.vocab, training_dataset, n_samples=1)
```

I looked at your source and this `training_dataset` is created and used, but not stored. Is there a different way to generate the interactive chart? And what is the **`kt.ctm.get_ldavis_data_format`** method for if it cannot be supplied with the data?

I realize I can use CTM to get this, but wanted to make sure I didn't miss some way to use Kitty as well.

**Comment by vinid** [comment]
Hello @marcmaxson!

yes you are right, there is no way to easily do this inside of kitty.

One thing I can do is store the dataset in the kitty object, in this way it should be possible to use that to create the ldavis plot.

Let me know if you want me to add this (or if you have done it, PRs are super welcome!)

**Comment by marcmaxson** [comment]
Yes, please add it. It doesn't need to default to saving this, as it would make the model bigger / use more memory. But if this can be used with pyLDAviz, I think more people would use it.

**Comment by vinid** [comment]
ok it's probably not the best fix but now [kitty](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/models/kitty_classifier.py#L39) has an option to return the dataset used for training
