### ISSUE TITLE
Wondering about files's locations

### ISSUE THREAD

**Issue by Carrie1337** [MilaNLProc/contextualized-topic-models#117]
Hey i ran this code below for the first time and i noticed that some stuff were being downloaded, can i know the location of these files?

```
from contextualized_topic_models.models.ctm import ZeroShotTM
from contextualized_topic_models.utils.data_preparation import TopicModelDataPreparation
from contextualized_topic_models.utils.data_preparation import bert_embeddings_from_file

text_for_contextual = [
    "hello, this is unpreprocessed text you can give to the model",
    "have fun with our topic model",
]

text_for_bow = [
    "hello unpreprocessed give model",
    "fun topic model",
]

qt = TopicModelDataPreparation("paraphrase-multilingual-mpnet-base-v2")

training_dataset = qt.fit(text_for_contextual=text_for_contextual, text_for_bow=text_for_bow)

ctm = ZeroShotTM(bow_size=len(qt.vocab), contextual_size=768, n_components=50)

ctm.fit(training_dataset) # run the model

ctm.get_topics(2)
```

**Comment by vinid** [comment]
Hi!

Downloaded files are generally stored in your .cache folder.

If you have linux this should be at /home/user/.cache

**Comment by Carrie1337** [comment]
I'm using Windows!

im guess that it is in C:\Windows\Temp?

**Comment by vinid** [comment]
The sentence-transformers source (that is the tool that downloads the models) seems to be saving things in the huggingface hub env variable. Check [here](https://huggingface.co/docs/transformers/installation?highlight=transformers_cache#cache-setup)
