### ISSUE TITLE
Using Deprecated `get_feature_names` Sklearn Call in Preprocessing

### ISSUE THREAD

**Issue by mxfeinberg** [MilaNLProc/contextualized-topic-models#119]
* Contextualized Topic Models version: 2.3.0 and 2.4.2
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description

Describe what you were trying to get done.

I was attempting to reproduce the Combined TM on Wikipedia Data (Preproc+Saving+Viz) (stable v2.3.0) example locally, and I was running into the following error during preprocessing. 

```
CountVectorizer' object has no attribute 'get_feature_names'
```

Tell us what happened, what went wrong, and what you expected to happen.

I tried using CTM versions 2.3.0 and 2.4.2, both with `sklearn` version `1.2.0`.  The issue is because more recent versions of `sklearn` have the function renamed `get_feature_names_out`. I believe this is a change from version `1.0` but you can see the change log [here](https://scikit-learn.org/stable/whats_new/v1.0.html).   I also noticed that `sklearn` is not explicitly required in the `requirements.txt` so a version is not specified.

### What I Did

I was able to fix the issue with the following change.

```
class WhiteSpacePreprocessingStopwords():
    ...
    def preprocess(self):
        ...
        temp_vocabulary = set(vectorizer.get_feature_names_out())
        ...

```

This is a simple and small fix, but I think it would also be a good idea to include with it some stricter package requirements.  I'm personally a fan of [pdm](https://github.com/pdm-project/pdm) which could help with avoiding issues like this in the future.  If the maintainers are open to some of these adjustments, I'd be happy to prepare a PR.

EDIT:

I also needed to make the same change to the `TopicModelDataPreparation` class.

**Comment by vinid** [comment]
Hello!

Happy yo get a PR on this!

Thanks so much!

**Comment by TudorAndrei** [comment]
@vinid I think this can also be closed
