### ISSUE TITLE
Numpy error evalation scores 

### ISSUE THREAD

**Issue by PhDPyBoss** [MilaNLProc/contextualized-topic-models#126]
* Contextualized Topic Models version: newest
* Python version: 3.6  (google collab)
* Operating System: Windows 10

### Description

Hi, 
I am trying to run the evaluation scores, but I keep getting this error:
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

I updated numby and pip, but it doesnt seem to work. I wonder if it has to do with the version of numpy that is imcompatible but I cant find if this is the case. 

### What I Did
from contextualized_topic_models.evaluation.measures import CoherenceNPMI

with open('preprocessed_documents.txt', "r") as fr:
    texts = [doc.split() for doc in fr.read().splitlines()] # load text for NPMI

npmi = CoherenceNPMI(texts=texts, topics=ctm.get_topic_lists(10))
npmi.score()

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```ValueError                                Traceback (most recent call last)

[<ipython-input-46-a8ce144de2dd>](https://localhost:8080/#) in <module>
----> 1 from contextualized_topic_models.evaluation.measures import CoherenceNPMI
      2 
      3 with open('preprocessed_documents.txt', "r") as fr:
      4     texts = [doc.split() for doc in fr.read().splitlines()] # load text for NPMI
      5 

6 frames

/usr/local/lib/python3.8/dist-packages/gensim/_matutils.pyx in init gensim._matutils()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by vinid** [comment]
Hi!

Which version of numpy are you using?

**Comment by vinid** [comment]
And is the error coming from one of the online colab notebooks?

**Comment by vinid** [comment]
Can you try to downgrade gensim to 4.2.0 and see if that solves the issue?

**Comment by PhDPyBoss** [comment]
this seems to work, thank you!

**Comment by PhDPyBoss** [comment]
Hi Federico,

I have another question; I was trying to run the CentroidDistance but I
cannot figure out some of the metrics. The
doc_distribution_original_language,
doc_distribution_unseen_language

don't really make sense to make. Do you have an exmaple on how to implement
this or could you give a bit more elaboration on the documentation?

Thanks!
Iris

**Comment by vinid** [comment]
Hello!

That measure is used to compare how similar topic distributions of the same documents are in different languages. You should find it better explained [here](https://aclanthology.org/2021.eacl-main.143/).

The definition of the two parameters you are looking at is as follows:
```
:param doc_distribution_original_language: numpy array of the topical
distribution of the documents in the original language
(dim: num docs x num topics)
:param doc_distribution_unseen_language: numpy array of the topical
distribution of the documents in an unseen language
(dim: num docs x num topics)
```

So, what you essentially need, is just two numpy arrays that contain the topic distribution for each document in the collection for the two languages.

What the measure is going to do is, for each pair of documents (one in the original language and one in the unseen language), is : 

1. get the topic of document 1 (original), get the topic of document 2 (unseen)
2. get the word list associated with document 1 and the word list associated with document 2
3. compare the two

Let me know if you have more questions

**Comment by PhDPyBoss** [comment]
Hi Federico,

Sorry to bother you again but I have one more question.
Currently I am working also with the Zero-Shot version, but some of the
code seems to be outdated.
When using the notebook for preprocessing, I get this error.

Looking in indexes: https://pypi.org/simple,
https://us-python.pkg.dev/colab-wheels/public/simple/ERROR: Could not
find a version that satisfies the requirement from (from versions:
none)ERROR: No matching distribution found for from

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-7-4741aaf45cbe> <https://localhost:8080/#> in <module>
   11      12 sp = WhiteSpacePreprocessingStopwords(documents,
stopwords_list=stopwords)---> 13 preprocessed_documents,
unpreprocessed_corpus, vocab, retained_indices = sp.preprocess()

/usr/local/lib/python3.8/dist-packages/contextualized_topic_models/utils/preprocessing.py
<https://localhost:8080/#> in preprocess(self)    113
vectorizer = CountVectorizer(max_features=self.vocabulary_size,
max_df=self.max_df)    114
vectorizer.fit_transform(preprocessed_docs_tmp)--> 115
temp_vocabulary = set(vectorizer.get_feature_names())    116     117
      preprocessed_docs_tmp = [' '.join([w for w in doc.split() if w
in temp_vocabulary])

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

I have tried to downgrade Ski-cit learn to version 1.2.1., but this does
not seem to fix it. I cannot change the code behind because it is closed.
Is this something that needs to be changed in the code on your end or do I
need to try something else?

Thank you again!

Best,
Iris

**Comment by vinid** [comment]
can you try to 

`pip install -U contextualized-topic-models` 

I have released a new version that should fix a couple of issues

**Comment by PhDPyBoss** [comment]
Thankyou, this works!

Op do 2 mrt. 2023 22:49 schreef Federico Bianchi ***@***.***>:

**Comment by PhDPyBoss** [comment]
Hi Federico,

I was running one of my experiments again, and I am getting another error.
[image: afbeelding.png]
re-installing numpy or seperate dependencies seems not to work. Do you know
what is going on here? I did not get this error before.

Thank you!
Best,
Iris

**Comment by vinid** [comment]
Hello, I don't think I can see the image, can you upload it again?

**Comment by PhDPyBoss** [comment]
Hi,
Yes of course, it is in the attachement.
thanks!

**Comment by vinid** [comment]
I keep not seeing this, can you try to upload it from GitHub and not with
the email reply?

**Comment by PhDPyBoss** [comment]
Hi, I attached the picture and also the code:
 
!pip install -U numpy --upgrade


`!pip install -U numpy --upgrade

from contextualized_topic_models.models.ctm import ZeroShotTM
from contextualized_topic_models.utils.data_preparation import TopicModelDataPreparation
from contextualized_topic_models.utils.preprocessing import WhiteSpacePreprocessing
import nltk`

results in error:
`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.24.3)

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-13-39bd94ed0dff>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 from contextualized_topic_models.models.ctm import ZeroShotTM
----> 4 from contextualized_topic_models.utils.data_preparation import TopicModelDataPreparation
      5 from contextualized_topic_models.utils.preprocessing import WhiteSpacePreprocessing
      6 import nltk

14 frames

[/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py](https://localhost:8080/#) in <module>
     21 from numpy.core import(
     22      intp, float32, empty, arange, array_repr, ndarray, isnat, array)
---> 23 import numpy.linalg.lapack_lite
     24 
     25 from io import StringIO

ImportError: numpy.core.multiarray failed to import


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
-------------------------------`
![Schermopname (14)](https://user-images.githubusercontent.com/125470965/235639107-593a5319-db8a-4b73-aba9-e6f261c469df.png)

**Comment by vinid** [comment]
I just tried the colab and imports work on my end.

Did you restart the colab after pip installing the ctm package?

**Comment by PhDPyBoss** [comment]
It is working now, thank you!
