### ISSUE TITLE
Error While Getting BERT Embeddings From File

### ISSUE THREAD

**Issue by pspahwa** [MilaNLProc/contextualized-topic-models#13]
Hey,

Hope you are well.

### Description

I was trying to take some text from some JSON files and then create topic models for those files. In particular, I was trying to calculate the topic distribution for each of the documents. 

I followed mostly from what was mentioned on [this issue ticket](https://github.com/MilaNLProc/contextualized-topic-models/issues/4) regarding the Pandas DataFrame and got it to work yesterday. However, today it is continuously giving me a weird error - "ValueError: Wrong shape for input_ids (shape torch.Size([1040])) or attention_mask (shape torch.Size([1040]))"

The error is when I try to get BERT embeddings from the file, in particular, when I run the following command:

training_bert = bert_embeddings_from_file("pre_documents.txt", "bert-base-nli-mean-tokens")

Below are the exact crash details.

```
ValueError                                Traceback (most recent call last)
<ipython-input-12-7cd62b310f6c> in <module>()
      6 handler.prepare()
      7 
----> 8 training_bert = bert_embeddings_from_file("pre_documents.txt", "bert-base-nli-mean-tokens") # I'm assuming the tweets are in english here.
      9 
     10 training_dataset = CTMDataset(handler.bow, training_bert, handler.idx2token)

7 frames
/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py in get_extended_attention_mask(self, attention_mask, input_shape, device)
    260             raise ValueError(
    261                 "Wrong shape for input_ids (shape {}) or attention_mask (shape {})".format(
--> 262                     input_shape, attention_mask.shape
    263                 )
    264             )

ValueError: Wrong shape for input_ids (shape torch.Size([1040])) or attention_mask (shape torch.Size([1040]))
```

For reference, I'm using Google Colab.

I'm pretty confused and any help would be greatly appreciated!

**Comment by joaorafaelm** [comment]
I'm getting the same error while running the example notebook on google colab https://github.com/MilaNLProc/contextualized-topic-models/blob/master/examples/multilingual-topic-modeling.ipynb

**Comment by joaorafaelm** [comment]
FYI, seems like breaking changes on transformers lib > 3.0.2:
```
!pip uninstall transformers -y
!pip install transformers==3.0.2
```
this should fix the errors... working notebook: https://github.com/joaorafaelm/notebooks/blob/master/multilang_topic_model.ipynb

**Comment by vinid** [comment]
Hi to both of you,

thanks for your comments! :)

I'm right now working on fixing the issue upgrading some of the packages but the tool is not passing the unit tests because of a current (temporary) issue in the [sentence-transformers package](https://github.com/UKPLab/sentence-transformers/issues/403).

I'll keep you posted!

**Comment by vinid** [comment]
The issue should be solved now, I'm releasing an updated version of the package. :)

**Comment by pspahwa** [comment]
Hey,

Yeah, the issue seems to be solved now. Thanks a lot!
