### ISSUE TITLE
How to Find coherence of this Topic and Model?

### ISSUE THREAD

**Issue by AbhinandanSingla** [MilaNLProc/contextualized-topic-models#131]
How to Find coherence of this Topic and Model?

Can you please give code for it?

**Comment by vinid** [comment]
Hello!

You can use any package to compute coherence metrics!

We also have some wrappers [here](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/evaluation/measures.py). You can also find a quick example [here](https://contextualized-topic-models.readthedocs.io/en/latest/evaluation.html#metrics-covered).

```python

from contextualized_topic_models.evaluation.measures import CoherenceNPMI

with open('preprocessed_documents.txt', "r") as fr:
    texts = [doc.split() for doc in fr.read().splitlines()] # load text for NPMI

npmi = CoherenceNPMI(texts=texts, topics=ctm.get_topic_lists(10))
npmi.score()

````
