### ISSUE TITLE
Custom Embedding vs Vocabulary

### ISSUE THREAD

**Issue by raymondsim** [MilaNLProc/contextualized-topic-models#133]
Hi,

I was wondering that if I used my own BART encoder to encode all documents and provide it as custom embedding, is it mandatory to provide corresponding vocabulary into combined CTM?

I remember there's an error if I do not provide vocab list that has the same size as custom embedding, and the way I modified the code is to provide list of vocab to the count vectorizer in .fit function for topicmodeldataprepration [here](https://github.com/MilaNLProc/contextualized-topic-models/blob/868f65753eb0711f45045e64d5e4e51cc3ad8356/contextualized_topic_models/utils/data_preparation.py#L122).

Thanks in advance!

**Comment by vinid** [comment]
Hello!

yea the vocab is needed to reconstruct the bag of words representation, it is the thing we use to build the topics.
On the other hand, you can pass any custom bag of words representation

**Comment by raymondsim** [comment]
Thanks for your reply.

The encoder I am using is BART encoder which uses BPE tokenization so many of the words have "Ġ" in front of it, when training topic model, my plan is to remove this character so that the topic model can learn with the vocab better. 

Will this be an issue that the vocab list is not 100% the same as vocab.json in the encoder I used?

**Comment by vinid** [comment]
which `text_for_bow` will you be giving to the model?

**Comment by raymondsim** [comment]
For now, I used preprocessed documents.

**Comment by vinid** [comment]
preprocessed how? these have to correspond to the vocab. if you use BART tokenizer there should not be any issue

**Comment by raymondsim** [comment]
I used WhiteSpacePreprocessingStopwords as shown in the example in colab.

So I guess what you mean is I should use BART tokenizer for data preprocessing here?

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/58366147/233757490-c7a60be0-776d-4d53-8092-caa80834dd0a.png">

**Comment by vinid** [comment]
you need to define your own preprocessing pipeline and data preparation yes :)

**Comment by raymondsim** [comment]
Do you mind providing some pointers on how I can integrate BART tokenizer into `preprocessing.py`? I thought providing vocab list from the encoder to `WhiteSpacePreprocessingStopwords` would be sufficient.

Thanks in advance :)

**Comment by vinid** [comment]
```And if I use the BART tokenizer for preprocessing pipeline, that means the vocab will have some special characters like "Ġ", will that affect the performance of topic model? Or is it okay as long as they are consistent?```

it depends fro what are you using this.

at an abstract level CTM takes in input two things:

1) a sentence
2) a preprocessed sentence

**Comment by vinid** [comment]
let me know if this helps
