### ISSUE TITLE
AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

### ISSUE THREAD

**Issue by yasminee99** [MilaNLProc/contextualized-topic-models#137]
* Contextualized Topic Models version: 2.30
* Python version: 3

from nltk.corpus import stopwords as stop_words

nltk.download('stopwords')

documents = [line.strip() for line in open(text_file, encoding="utf-8").readlines()[0:2000]]

stopwords = list(stop_words.words("english"))

sp = WhiteSpacePreprocessingStopwords(documents, stopwords_list=stopwords)
preprocessed_documents, unpreprocessed_corpus, vocab, retained_indices = sp.preprocess()
```
AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'.
```

**Comment by vinid** [comment]
Hello!

you are using an old version of CTM with a newer version of sklearn. 

You should update to the latest CTM version,

```pip install -U contextualized-topic-models```

**Comment by yasminee99** [comment]
thank you !
