### ISSUE TITLE
Testing with custom embedding

### ISSUE THREAD

**Issue by Ton-moy** [MilaNLProc/contextualized-topic-models#139]
I trained the CombinedTM model with 600k documents where I used custom embedding and the vocabulary size was 628221. After training, I saved the model. To get topic distribution for another 500 documents, I created a testing dataset with custom embedding and loaded the saved model. However, when passing the testing dataset through the 'get_doc_topic_distribution()' function, I  got many Deprecation Warnings and the following error below: 
**Error:**      RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x645224 and 1256442x100)

**My Code:**
![Screenshot 2023-07-02 170719](https://github.com/MilaNLProc/contextualized-topic-models/assets/65665095/3181be66-a958-4100-bdc5-9c6e3c602533)

**Error:** 

![Screenshot 2023-07-02 174553](https://github.com/MilaNLProc/contextualized-topic-models/assets/65665095/b508b84e-f5b3-416a-a528-92a713d2c559)

Can you please help me out in this case? 

Thanks in advance.

**Comment by vinid** [comment]
Can you print again the shape of all your data?

lf_embeddings, bow_embeddings, id2token for both your training and test (so
six elements)

**Comment by Ton-moy** [comment]
**Training:** 

![Screenshot 2023-07-02 182610](https://github.com/MilaNLProc/contextualized-topic-models/assets/65665095/e71a760a-6245-4d62-9331-753d77e0495f)


**Testing:**

![Screenshot 2023-07-02 182451](https://github.com/MilaNLProc/contextualized-topic-models/assets/65665095/8d1026e0-723f-4843-bee9-f19055f9a591)

**Comment by vinid** [comment]
The second dimension of your bow sizes do not match.

They should both be 628221. You need to use the same CountVectorizer for
both

**Comment by Ton-moy** [comment]
Using the same CountVectorizer resolves the issue. However, it gives deprecation warning 500 times for each document. So for 500 documents, it prints the following warning 500*500 = 250000 times. It takes too much time to run the code for the get_doc_topic_distribution() function that seems very unusual comparing with training time. As I have a large number of documents (e.g., 700k) for testing, the warning will create bottleneck if I want to get the topic distribution for those documents. Can you help please me to avoid the warning? Is it normal for get_doc_topic_distribution() function to take more time than training?

**Warning:**   
/users/thasan1/.conda/envs/tonmoy/lib/python3.11/site-packages/contextualized_topic_models/datasets/dataset.py:32: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
  if type(self.X_bow[i]) == scipy.sparse.csr.csr_matrix:


Thanks in advance.

**Comment by vinid** [comment]
n_samples is not the number of training/testing examples. It is the number
of samples to take from the distribution. Try putting 20

For the warnings, it should be enough to update sklearn to a more recent
version

**Comment by Ton-moy** [comment]
My sklearn version was 1.0 and upgraded it to the latest version 1.3.0, but still getting the warning. I also tried with 1.1.0, 1.2.0, but didn't help. Can you mention any specific version for sklearn that can help in this issue? My contextualized-topic-models version is 2.3.0

**Comment by vinid** [comment]
it's probably some other package using old sklearn functionalities.

you can try to see if 

`pip install -U contextualized-topic-models` helps to reduce the warnings.

Worst case scenario, you can temporarily disable warnings using:

```
import warnings
warnings.filterwarnings("ignore")```
