### ISSUE TITLE
Expected more than 1 value per channel when training

### ISSUE THREAD

**Issue by aritzzz** [MilaNLProc/contextualized-topic-models#16]
I am following the instructions to fit the model. However,  I am getting this error:
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 50])

How to resolve this? What does this mean? 

```
from contextualized_topic_models.models.ctm import CTM
from contextualized_topic_models.utils.data_preparation import TextHandler
from contextualized_topic_models.utils.data_preparation import bert_embeddings_from_file
from contextualized_topic_models.datasets.dataset import CTMDataset

handler = TextHandler("topic_tst.txt")
handler.prepare() # create vocabulary and training data

training_bert = bert_embeddings_from_file("topic_tst.txt", "./roberta-large-nli-mean-tokens")


training_dataset = CTMDataset(handler.bow, training_bert, handler.idx2token)

ctm = CTM(input_size=len(handler.vocab), bert_input_size=1024, inference_type="combined", n_components=50)

ctm.fit(training_dataset) # run the model
```

**Comment by vinid** [comment]
Hi @aritzzz!

would you mind sharing the file you are using?

I just tried an example with a sample file that looks like [this](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/data/sample_text_document) from a fresh virtual environment and it worked (with "./roberta-large-nli-mean-tokens")

Can you also tell me which version of the package you are using? Did you install this in a fresh virtual environment?

thanks!

**Comment by aritzzz** [comment]
Thanks for the prompt response!
This is my [file](https://gist.github.com/aritzzz/6a8d8f0f39854087ed382f2e304b5af2). Technically, it contains only one line (document). 

Versions:
torch                     1.6.0
python                    3.7.7
sentence-transformers     0.3.5.1
contextualized-topic-models 1.4.3

And, I did not install it in a fresh environment.

**Comment by vinid** [comment]
The fact that there is only one document in the file might be the problem. See [here](https://discuss.pytorch.org/t/error-expected-more-than-1-value-per-channel-when-training/26274). 

Could you try running the model on a file that contains multiple documents (lines)?

**Comment by aritzzz** [comment]
Update: Add other lines in the file does solve the problem. Thanks!

**Comment by vinid** [comment]
Yay! That's great!

I'm closing the issue then :)
