### ISSUE TITLE
How to use the  model trained by this algo to  predict topics

### ISSUE THREAD

**Issue by marcusau** [MilaNLProc/contextualized-topic-models#17]
* Contextualized Topic Models version:
* Python version:
* Operating System:

### Description

Hi,  appreciate this module very much.

Just two simple questions:

1. I have used the algo to train my own model and saved it to the directory.

May I ask how to use the trained model to predict topics for my documents outside the training corpus??

2. Do the trained model could facilitate textual similarities ,e.g. given a topic word or paragraph,  the model would tell us the prob of which topics are closer to the query item?

Thanks a lot.

**Comment by vinid** [comment]
Hi @marcusau!

Happy you like our package!

1. Yes! you can take a look at [this](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/examples/multilingual-topic-modeling.ipynb) notebook. You'll see that the model can be used to do prediction for documents in other languages. You can use the same structure to predict the topic for your documents (make sure you use the same BERT model you used in training). What you will need to do is to create a new dataset with your test documents (saved to a file) and then run the prediction pipeline of the model.

2. Could you add some more details of what you would like to do (so I can get a better view of the task)? One thing you could do is to pass the text describing the query item and get the topic distribution. In this case you will get the most probable topic for that item.

I'm happy to add details/be more specific if something is not clear!

**Comment by vinid** [comment]
I'm closing this issue for now! :)
