### ISSUE TITLE
Code for topic prediction in the example

### ISSUE THREAD

**Issue by VespaLan** [MilaNLProc/contextualized-topic-models#19]
Thanks for sharing the code! A little bit confused about the code for the topic prediction in [https://github.com/MilaNLProc/contextualized-topic-models/blob/master/examples/topic-modeling.ipynb](url) So if I understand it right(I am new to this field and hopefully I got it), is it correct that one line in the `GoogleNews.txt` refers to one document? For the examples above, the topics the model generates for document `nokia lumia launch` are `['moto', 'xbox', 'camera', 'surface', 'review']`. These words didn't appear in the eighth document.

**Comment by silviatti** [comment]
Hi,
Yes, each line of the text file corresponds to one document. 

As you can see, documents in the Google News dataset are very short. So, it is likely that the words in a particular document do not appear in the top 5 most likely words of a given topic. If you like to get more than 5 words representing a topic, you can change the value of the parameter `k` of the function `get_topic_lists(k)`. 

Moreover, even if the words "_nokia lumia launch_" of the document do not perfectly match the topic's words, it is clear that the topic represented by the words "_moto xbox camera surface review_" refers to technology (_xbox_ and _surface_ are actually two Microsoft's products as well as _lumia_). So, I'd say that the topic prediction works fine. 

I hope this helped :) 

Silvia

**Comment by VespaLan** [comment]
I see. Thanks for your quick response!
