### ISSUE TITLE
method _init_nn()

### ISSUE THREAD

**Issue by sidneyaraujomelo** [MilaNLProc/contextualized-topic-models#20]
* Contextualized Topic Models version: 1.5.0
* Python version: 3.7
* Operating System: ubuntu 18.04

Hello! what exactly is needed for this not yet implemented method? https://github.com/MilaNLProc/contextualized-topic-models/blob/c9c244bdeb1d0034e38e1033daaa64fdfa4946f6/contextualized_topic_models/models/ctm.py#L381
Wouldn't the line below overwrite the initial parameters of the DecoderNetwork?

Thanks in advance!

**Comment by vinid** [comment]
Hello!

This is a leftover from the old implementation of the variational topic model. We are right now rewriting the save and load methods and we will hopefully include those in the next release :).

**Comment by sidneyaraujomelo** [comment]
Thanks, Federico! I'll stay tuned for the next release.
