### ISSUE TITLE
Different coherence measures

### ISSUE THREAD

**Issue by Der-Rapha** [MilaNLProc/contextualized-topic-models#23]
I am experimenting with your code to draw some comparisons to classic LDA and other topic modeling algorithms.

Also not the most reliable measure, I wanted to look at the various coherence measures.

In you measure.py file you are using the CoherenceModel from genism, but you are also specifying the 'c_npmi' as measure.

1. I couldn't figure out how to adjust it to 'c_v' & 'u_mass'. Is it even possible? If not, could you please explain why?

2. I always get the following error message when trying to compute the 'c_npmi':

```
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/gensim/models/coherencemodel.py in _ensure_elements_are_ids(self, topic)
    444         try:
--> 445             return np.array([self.dictionary.token2id[token] for token in topic])
    446         except KeyError:  # might be a list of token ids already, but let's verify all in dict

/opt/conda/lib/python3.7/site-packages/gensim/models/coherencemodel.py in <listcomp>(.0)
    444         try:
--> 445             return np.array([self.dictionary.token2id[token] for token in topic])
    446         except KeyError:  # might be a list of token ids already, but let's verify all in dict

KeyError: 'lan'
```

Thanks in advance.

All the best

**Comment by silviatti** [comment]
Hi Rafael!

In the current version of the library, you can only use the NPMI coherence. I have just updated the GitHub repo and included the other three implemented coherences from gensim. So you can import `CoherenceUMASS`, `CoherenceUCI`, `CoherenceCV` (and `CoherenceNPMI`, as before). They have the same parameters as NPMI's, so it must be easy to try them out.  We are going to add them to the next library release in a few days, but if you need to use them as soon as possible, you can directly use their implementation in the Github repository. 

Concerning the error about the computation of NPMI, it seems that some topic words are not present in the texts on which you compute the coherence. This may happen when you are using an external corpus to compute coherence. Please, make sure that all the top-words in the topics are also included in the corpus that you are using for evaluating the coherence. Unfortunately, gensim does not handle out-of-vocabulary words. 

Let me know if this solved your problems :)

Silvia
