### ISSUE TITLE
BoW and Contextual Embeddings have different sizes

### ISSUE THREAD

**Issue by Der-Rapha** [MilaNLProc/contextualized-topic-models#26]
Whenever I try to run the CTMDataset, I get the following error message.

`Exception: Wait! BoW and Contextual Embeddings have different sizes! You might want to check if the BoW preparation method has removed some documents. `

I am not sure how to solve this problem. When I convert the preprocessed and not_preprocessed column in my dataframe to a txt.file they have the same length without any NaN or empty strings. But after the handler.prepare() and bert_embdeddings_from_file, they have a different length.

I hope that I formulated my problem relatively clearly.

Looking forward to some feedback. If you need more information, please let me know!

Many thanks

**Comment by vinid** [comment]
Hi @Der-Rapha!

Is it possible for you to share the files you are using? there could be some leftover "\n" in the pandas dataframe cells that make the two files having a different lenght (not sure if you already did that, but have you tried to run `wc -l` on the two files, the preprocessd and unpreprocessed ones?)

Thanks :)

**Comment by Der-Rapha** [comment]
Hey @vinid,

thanks for the fast response.

I've used the `wc- l` and indeed, they have a different size. However, I again made sure to get rid of the "\n" within the text.

Do you have another idea? Otherwise, I might be able to share the data with you in private.

Thank you!

**Comment by vinid** [comment]
Ok, so the problem is in the files since you have a different number of lines for each. If you can send me the data it would be great so I can try myself and get back to you asap :)

**Comment by Der-Rapha** [comment]
Okay, great. Highly appreciated!

You just got an email.

**Comment by vinid** [comment]
*solved by email
