### ISSUE TITLE
Import Error: Cannot import ZeroShotTM error

### ISSUE THREAD

**Issue by Riccardo7-DS** [MilaNLProc/contextualized-topic-models#29]
* Contextualized Topic Models version: 1.5.3
* Python version: 3.6
* Operating System: Linux

### Description

Hello, I got an error "ImportError: cannot import name 'ZeroShotTM'" when running the command: 

from contextualized_topic_models.models.ctm import ZeroShotTM
 

My packages version:

transformers: 3.1.0

sentence-transformer: 0.3.6

torch: 1.6.0

**Comment by silviatti** [comment]
Hi :)

ZeroShotTM has been introduced from version 1.6.0 of the package. You just need to update the package from version 1.5.3 to 1.6.0.  

Silvia

**Comment by Riccardo7-DS** [comment]
Thanks, for your help. I just realized this.


Riccardo
