### ISSUE TITLE
some little error

### ISSUE THREAD

**Issue by SomeoneNotLikeYou** [MilaNLProc/contextualized-topic-models#34]
* Contextualized Topic Models version:
* Python version:3.6
* Operating System: win10

### Description

When I run the Contexutalized Topic Modeling with your Documents (with preprocessing) have error
error happen on 29 line
![image](https://user-images.githubusercontent.com/50167423/101489936-9c9abc80-399c-11eb-8a56-df567a827829.png)

### What I Did

![image](https://user-images.githubusercontent.com/50167423/101489981-a8867e80-399c-11eb-9565-23d9f87c5f5c.png)

thank you very much

**Comment by silviatti** [comment]
Hi!

If you haven't already, please update the `contextualized-topic-models` package (you forgot to mention the package version). 

Your issue seems to be related to the download of the pre-trained model. Referring to [this solution](https://github.com/UKPLab/sentence-transformers/issues/30), you should delete the files in `C:\\Users\\39852/.cache\\torch\\sentence_transformers\\` and try to reload the model using our method `bert_embeddings_from_list()` or using the following instruction `model = SentenceTransformer('bert-base-nli-stsb-mean-tokens')`. 

Silvia

**Comment by SomeoneNotLikeYou** [comment]
> Hi!
> 
> If you haven't already, please update the `contextualized-topic-models` package (you forgot to mention the package version).
> 
> Your issue seems to be related to the download of the pre-trained model. Referring to [this solution](https://github.com/UKPLab/sentence-transformers/issues/30), you should delete the files in `C:\\Users\\39852/.cache\\torch\\sentence_transformers\\` and try to reload the model using our method `bert_embeddings_from_list()` or using the following instruction `model = SentenceTransformer('bert-base-nli-stsb-mean-tokens')`.
> 
> Silvia

Your method is very effective, thank you very much. 
I have a request, whether the multi-language model and the single-language model can be divided into two pages. 
This is convenient for novices to learn, thank you very much.

**Comment by vinid** [comment]
Hi @SomeoneNotLikeYou!

Happy you solved your problems :)

we are always looking for ways to improve our documentation! You'd like us to have two different "tutorials" one for cross-lingual and one for single-language? So the readme would be split into two parts?

Thanks!

**Comment by SomeoneNotLikeYou** [comment]
Consider that your code and readme are divided into two pages. Your ideas and code are very good, which helped me a lot. However, the existing layout is not clear enough for novices.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MilaNLProc/contextualized-topic-models"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 晚上7:09
收件人:&nbsp;"MilaNLProc/contextualized-topic-models"<contextualized-topic-models@noreply.github.com&gt;;
抄送:&nbsp;"@Zhangmin"<398521171@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MilaNLProc/contextualized-topic-models] some little error (#34)





 
Hi @SomeoneNotLikeYou!
 
Happy you solved your problems :)
 
we are always looking for ways to improve our documentation! You'd like us to have two different "tutorials" one for cross-lingual and one for single-language? So the readme would be split into two parts?
 
Thanks!

**Comment by vinid** [comment]
thanks a lot! we will work on this!

**Comment by SomeoneNotLikeYou** [comment]
> thanks a lot! we will work on this!

I want to use Chinese dataset, what can I do

**Comment by silviatti** [comment]
See issue #37
