### ISSUE TITLE
I want to ues Chinese dataset , what can  I do?

### ISSUE THREAD

**Issue by SomeoneNotLikeYou** [MilaNLProc/contextualized-topic-models#37]
* Contextualized Topic Models version:
* Python version: 3.6
* Operating System: windows
@vinid @silviatti

**Comment by vinid** [comment]
Hi @SomeoneNotLikeYou,

Do you have a colab notebook and some data we can look at?

(beware I know almost nothing about Chinese, so I might say things that are not completely applicable to your use case/completely true)

Our BoW part is currently based on a whitespace tokenizer (see for example [here](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/utils/preprocessing.py#L35)).

This means that given in input a sentence like "I like food", our BoW part gets this as ["I", "like", "food"]. You will need to find a way to replicate this behavior in Chinese. (See also [this](https://medium.com/the-artificial-impostor/nlp-four-ways-to-tokenize-chinese-documents-f349eb6ba3c3))

So:

- Given a Chinese sentence, you should find a way to first segment it. What you should be able to get is create a list of "space separated" tokens and you can give these to the `text_for_bow` parameter. Just to recap: from Chinese chars to white space separated sentences of Chinese tokens.

- to the `text_for_bert` parameter, you can feed the original documents (I think, but you might need to check a Chinese BERT model to be sure about this).

- Obviously, you need to use a Chinese BERT model: huggingface.co/models

**Comment by vinid** [comment]
closing this for now, feel free the write again if you have problems :)
