### ISSUE TITLE
ZeroShot Model: Predict topics of the documents in unseen languages

### ISSUE THREAD

**Issue by VikaNa** [MilaNLProc/contextualized-topic-models#41]
* Contextualized Topic Models version: 1.7.1
* Python version: 3.7.3
* Operating System: Windows

I trained a ZeroShot model in one language and, now, I am trying to predict topics in another language using  get_doc_topic_distribution(n_samples = 10) . However, it takes much longer as compared to the training dataset. Both datasets are about the same size, namely 800000 texts. Now, it has been running for almost 24 h.
Could you tell me, from your experience, whether it is normal?  Or should I set lower n_samples number?      

Thank you!

**Comment by vinid** [comment]
Hello, 

are you running this on GPU?

**Comment by VikaNa** [comment]
Hi :) 
I have a Intel Core i3 CPU on which I run this. 
I only have a Intel UHD 620 GPU...

**Comment by vinid** [comment]
It should not take so much time.

One thing that might be consuming is the use of the bow for the testing language (this is passed through the entire model, but it is never used). Could you try and preprocess that bow?

a slightly modified version of what we have in the readme should look like this:

```python

list_of_unpreprocessed_SPANISH_documents = [
    "hola, bienvenido",
]

list_of_preprocessed_SPANISH_documents = [
    "hola bienvenido",
]

qt = QuickText("distiluse-base-multilingual-cased",
                text_for_bert=list_of_unpreprocessed_SPANISH_documents,
                text_for_bow=list_of_preprocessed_SPANISH_documents)

testing_dataset = qt.load_dataset()

# n_sample how many times to sample the distribution (see the doc)
ctm.get_thetas(testing_dataset, n_samples=20) # returns a (n_documents, n_topics) matrix with the topic distribution of each document
```

This won't change the results but should make the process a little bit faster

**Comment by VikaNa** [comment]
Ok, thank you! I'll try this out. 

One more thing: I also used pre-trained BERT embeddings for the testing language. As the QuickText's method  load_pre_trained_contextualized() didn't work, I did it as follows:

```python
qt_ru = QuickText("distiluse-base-multilingual-cased", 
                  text_for_bert=ru_documents,
                  text_for_bow=ru_documents)
qt_ru.data_bert = emb_ru
testing_dataset = qt_ru.load_dataset() 
```

So now, I am going to pass preprocessed ru_documents (punctuation, stopwords removed etc.) for text_for_bow to reduce the dimensionality of the test data. I hope that will work.

**Comment by vinid** [comment]
the `load_pre_trained_contextualized` is not in the version 1.7.1, if you want to use it you need to install it directly from the master repository.

You also might want to check if the distiluse-base-multilingual-cased model supports the language you are [testing](https://www.sbert.net/examples/training/multilingual/README.html)

**Comment by VikaNa** [comment]
Hi @vinid :)
I just wanted to let you know that preprocessing the testing data helped! I reduced the vocabulary size of the testing dataset to under 2000 words. The process of predicting the topics just took 1 h (with pre-trained BERT Embeddings).  
Thank you for your help!

P.S. The languages that I am using are supported by distiluse-base-multilingual-cased. As I said, I have already had the BERT embeddings for my datasets for other implications.

**Comment by vinid** [comment]
That's great! Happy it worked :)

Thank you for the feedback, we will update the readme adding more details about this process :)
