### ISSUE TITLE
AttributeError: 'ZeroShotTM' object has no attribute 'get_doc_topic_distribution'

### ISSUE THREAD

**Issue by subho22** [MilaNLProc/contextualized-topic-models#45]
AttributeError: 'ZeroShotTM' object has no attribute 'get_doc_topic_distribution'

**Comment by vinid** [comment]
which version of the package are you using?

**Comment by subho22** [comment]
1.6.0

**Comment by vinid** [comment]
yes, `ctm.get_thetas() `

https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/models/ctm.py#L247

**Comment by subho22** [comment]
Thanks!!
