### ISSUE TITLE
Saving the zero shot model

### ISSUE THREAD

**Issue by subho22** [MilaNLProc/contextualized-topic-models#48]
* Contextualized Topic Models version:1.6.0
* Python version:
* Operating System:

Can I use the pickle module in python to save the Zerohot model

**Comment by vinid** [comment]
Yes, in theory, you should be able to pickle the python object directly.

This might not be the [perfect way](https://pytorch.org/tutorials/beginner/saving_loading_models.html) of doing this, but it works for most cases.

You can also use the `.save()` and `.load()` [functions](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/models/ctm.py#L379) of the ZeroShotTM class, they are still experimental but I never got problems with those

**Comment by subho22** [comment]
Thanks Vinid
