### ISSUE TITLE
NameError: name 'tp' is not defined

### ISSUE THREAD

**Issue by tobimichigan** [MilaNLProc/contextualized-topic-models#49]
* Contextualized Topic Models version:
* Python version:
* Operating System:
%%capture
!pip install contextualized-topic-models==1.8.1
!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

### Description

```
qt = TopicModelDataPreparation("bert-base-nli-mean-tokens")
training_dataset = tp.create_training_set(unpreprocessed_corpus_for_contextual, preprocessed_documents_for_bow)

```
### What I Did

```
NameError                                 Traceback (most recent call last)

<ipython-input-11-de13bb34ab74> in <module>()
      1 qt = TopicModelDataPreparation("bert-base-nli-mean-tokens")
----> 2 training_dataset = tp.create_training_set(unpreprocessed_corpus_for_contextual, preprocessed_documents_for_bow)

NameError: name 'tp' is not defined
```
@vinid @silviatti @dnozza

**Comment by vinid** [comment]
Hello!

the variable `qt` in the line `qt = TopicModelDataPreparation("bert-base-nli-mean-tokens")` should instead be `tp`. Thus, you need to update your line of code like this:

```tp = TopicModelDataPreparation("bert-base-nli-mean-tokens")```

Where did you find this code? I am pretty sure we left some wrong indication when we changed the variable names, could you point me to that so I can fix this typo? Thanks a lot :)

**Comment by vinid** [comment]
Feel free to open this again if you need help :)
