### ISSUE TITLE
Problematic matching between BOW and LM embeddings in CTMDataset

### ISSUE THREAD

**Issue by gsarti** [MilaNLProc/contextualized-topic-models#5]
* Contextualized Topic Models version: 1.3.1
* Python version: 3.6.8
* Operating System: Ubuntu 18.04 LTS

### Description

Not properly a bug, but a possibly problematic behavior worth highlighting:

When initializing the `CTMDataset` object, there are no checks to ensure that both the BOW and contextual embeddings have the same length. This wouldn't normally be a problem, except that documents can get filtered out from the BOW list during `TextHandler.prepare()` if they don't contain any word in the vocabulary due to the condition `if np.sum(x[x != np.array(None)]) != 0` in `get_bag_of_words`. The result is that there is a mismatch between BOW and contextual embedding, and CTMDataset `__getitem__` accesses wrong elements.

### What I Did

I took the raw first 50'000 sentences of the [English Europarl corpus](http://www.statmt.org/europarl/) (next referred to as "unpreprocessed documents") and did some standard preprocessing (lemmatization, POS-based filtering) obtaining a set of sentences in a format similar to the one used in your GoogleNews examples ("preprocessed documents").

Following the provided examples, I use the `prepare` method of the `TextHandler` class to obtain the BOW representation of each preprocessed document. After that, I generate the contextual embeddings from unpreprocessed documents using the `bert_embeddings_from_file` or `bert_embeddings_from_list` methods and use both to initialize the `CTMDataset`.

### Additional precisions and possible solutions

Despite the issue, the fitting process for the CTM with mismatched sizes runs without crashing. I didn't investigate this specifically, but I assume it is somehow related to some default batching behavior in torch.

A quick possible fix for the reported issue would be to simply raise an exception if # of BOW and contextual embeddings do not match in the `CTMDataset` initializer, making users aware of the problem. A more complex albeit possibly better alternative could be to avoid filtering empty BOWs in the `get_bag_of_words` method and do it in the `CTMDataset` initializer, removing the corresponding contextual embedding to preserve the correct matching.

**Comment by vinid** [comment]
Hi Gabriele!

thanks a lot for your comment and for finding this issue! It is definitely a behavior that might cause problems/unwanted results.

As you suggested, I'll update the code to throw an exception if the two inputs have different lengths. I'd prefer this because I was wondering if the second solution might make users wonder why some documents have been removed (I'd prefer this to be an explicit behavior and not a silent one).

Thanks again! :)

**Comment by gsarti** [comment]
Awesome, thanks for the fast reply! I'm closing the issue then!
