### ISSUE TITLE
Error after running training_dataset = qt.load_dataset() in the colab zero shot example

### ISSUE THREAD

**Issue by sersoage** [MilaNLProc/contextualized-topic-models#50]
* Contextualized Topic Models version:
* Python version:
* Operating System:

### Description
I am getting the following error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-8d29e78aec05> in <module>()
----> 1 training_dataset = qt.load_dataset()

AttributeError: 'TopicModelDataPreparation' object has no attribute 'load_dataset'

After running training_dataset = qt.load_dataset() in the colab Contexutalized Topic Modeling with your Documents (with preprocessing).

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by silviatti** [comment]
Hi! 
Thank you for reporting this. We've realized that the link was pointing to an obsolete notebook. I've just updated the readme file with the right notebook. Otherwise, you can find it [here](https://colab.research.google.com/drive/13YhYgJN9EjSQw5bsZYzMaaiNKQpt_SQn?usp=sharing).

Bye,

Silvia

**Comment by sersoage** [comment]
Thanks closing the issues
