### ISSUE TITLE
dimension mismatch during inference

### ISSUE THREAD

**Issue by ashispapu** [MilaNLProc/contextualized-topic-models#53]
Thanks for sharing the code. 
I am trying to do a contextual topic modelling on a custom dataset as below.

```
tp = TopicModelDataPreparation("bert-base-nli-mean-tokens")
training_dataset = tp.create_training_set(text_for_contextual=unpreprocessed_corpus, text_for_bow=preprocessed_documents)
ctm_1 = CombinedTM(input_size=len(tp.vocab), bert_input_size=768, n_components=5, num_epochs=15)
ctm_1.fit(training_dataset)

test_documents = ['sentece 1', 'sentence 2']
sp = WhiteSpacePreprocessing(test_documents, stopwords_language='english')
test_preprocessed_documents, test_unpreprocessed_corpus, vocab = sp.preprocess()
testing_dataset = tp.create_training_set(text_for_contextual=test_unpreprocessed_corpus, text_for_bow=test_preprocessed_documents)
test_topics_predictions_1 = ctm_1.get_thetas(testing_dataset)
```
It gives me below dimension mismatch error.
``` 
    RuntimeError: mat1 dim 1 must match mat2 dim 0 
    contextualized_topic_models/networks/inference_network.py in forward(self, x, x_bert)
     128         x = torch.cat((x, x_bert), 1)
--> 130         x = self.input_layer(x)
``` 
Tried with another way to creat the test dataset, however it also  gets the same error.
```
test_set = tp.create_test_set(test_documents)
test_topics_predictions_1 = ctm_1.get_doc_topic_distribution(test_set)
And
test_topics_predictions_1  = ctm_1.get_thetas(test_set)
```
Am I missing anything here while doing the inference. Please share your input how to do the inference on a CTM trained model in real time.

**Comment by vinid** [comment]
Hello @ashispapu!

when you create the test set, you need to use the respective method, otherwise, the BoW won't be the same. So, use `tp.create_test_set` for the testing.

```testing_dataset = tp.create_test_set(testing_contextual_documents, testing_bow_documents)```

Refer to this [notebook](https://colab.research.google.com/drive/1wVWHe8xHasnUbzNs40MwlkJsUhvN98se?usp=sharing) to see an example of training and testing.

Hope this helps!

**Comment by ashispapu** [comment]
Thank you for the response. It solves.
