### ISSUE TITLE
Hugging Face Model for Embedding

### ISSUE THREAD

**Issue by dmolina2** [MilaNLProc/contextualized-topic-models#54]
* Contextualized Topic Models version: 1.8.2
* Python version: 3.6
* Operating System: Windows 10

### Description

Hey guys... I'm trying to use CTM's for Topic Modeling answers of a survey. This texts are in spanish so I want to use a spanish pre trained HuggingFace Model as it says in the repository: "In general, our package should be able to support all the models described in the sentence transformer package and in HuggingFace." 

Could you give an example how to export and use for embedding an HugginFace model like, for example:

https://huggingface.co/dccuchile/bert-base-spanish-wwm-uncased

It'd incredible if I can export this model, since it works very good in other NLP tasks.

Thanks!

**Comment by vinid** [comment]
Hello @dmolina2! :)

Yes, you can! and you can have this in both CombinedTM and ZeroShotTM.

The only thing you need to do is to use the Spanish model when you create the embeddings:

```python
qt = TopicModelDataPreparation("dccuchile/bert-base-spanish-wwm-uncased")
```
You can refer to [this link](https://www.sbert.net/examples/applications/computing-embeddings/README.html#sentence-embeddings-with-transformers) to check how these embeddings are created!

**Comment by dmolina2** [comment]
Thanks! Very clear!
