### ISSUE TITLE
Loading Model for Inference without train everytime

### ISSUE THREAD

**Issue by dmolina2** [MilaNLProc/contextualized-topic-models#59]
* Contextualized Topic Models version:
* Python version:
* Operating System:

### Description

Hello!

I have a model that is predicting very well the topics so I want to set it on production. While I was starting this I came with the following doubt. I'm loading my pretrained model and that's ok, but when I create my test_data I have an issue related with the data processed for the BoW:

```
def create_test_set(self, text_for_contextual, text_for_bow=None):

        if self.contextualized_model is None:
            raise Exception("You should define a contextualized model if you want to create the embeddings")

        if text_for_bow is not None:
            test_bow_embeddings = self.vectorizer.transform(text_for_bow)
        else:
            # dummy matrix
            test_bow_embeddings = scipy.sparse.csr_matrix(np.zeros((len(text_for_contextual), 1)))
        test_contextualized_embeddings = bert_embeddings_from_list(text_for_contextual, self.contextualized_model)

        return CTMDataset(test_bow_embeddings, test_contextualized_embeddings, self.id2token)

    def create_validation_set(self, text_for_contextual, text_for_bow=None):
        return self.create_test_set(text_for_contextual=text_for_contextual, text_for_bow=text_for_bow)
```

Here in your **data_preparation.py** script the `create_test_set` function has the variable _text_for_bow_ is optional and it makes sense as I don't want to train every time my model (that means to create the create the training_dataset everytime) where the CountVectorizer will be created. Anyway, if I only put my text_for_contextual and then I do this:

`predictions = ctm.get_doc_topic_distribution(testing_dataset, n_samples=10)`

I get an error of dimension... (After that I created a training set with the `create_training_set` and then my test_set with the _text_for_bow_ = processed_test_set and it went well.

Any advice?? I will appreciate beacause my main objective here is to predict whithout train every time.

Thanks.

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-210-61941325c3e1> in <module>
      1 testing_dataset_prueba = qt.create_test_set(unpreprocessed_documents_test[:1000]) # create dataset for the testset
----> 2 predictions_prueba = ctma.get_doc_topic_distribution(testing_dataset_prueba, n_samples=10)

~\AppData\Roaming\Python\Python38\site-packages\contextualized_topic_models\models\ctm.py in get_doc_topic_distribution(self, dataset, n_samples)
    289                     # forward pass
    290                     self.model.zero_grad()
--> 291                     collect_theta.extend(self.model.get_theta(X, X_bert).cpu().numpy().tolist())
    292 
    293                 pbar.update(1)

~\AppData\Roaming\Python\Python38\site-packages\contextualized_topic_models\networks\decoding_network.py in get_theta(self, x, x_bert)
    126         with torch.no_grad():
    127             # batch_size x n_components
--> 128             posterior_mu, posterior_log_sigma = self.inf_net(x, x_bert)
    129             posterior_sigma = torch.exp(posterior_log_sigma)
    130 

~\Miniconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\AppData\Roaming\Python\Python38\site-packages\contextualized_topic_models\networks\inference_network.py in forward(self, x, x_bert)
    126         x_bert = self.adapt_bert(x_bert)
    127         x = torch.cat((x, x_bert), 1)
--> 128         x = self.input_layer(x)
    129 
    130         x = self.activation(x)

~\Miniconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\Miniconda3\lib\site-packages\torch\nn\modules\linear.py in forward(self, input)
     91 
     92     def forward(self, input: Tensor) -> Tensor:
---> 93         return F.linear(input, self.weight, self.bias)
     94 
     95     def extra_repr(self) -> str:

~\Miniconda3\lib\site-packages\torch\nn\functional.py in linear(input, weight, bias)
   1688     if input.dim() == 2 and bias is not None:
   1689         # fused op is marginally faster
-> 1690         ret = torch.addmm(bias, input, weight.t())
   1691     else:
   1692         output = input.matmul(weight.t())

RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x2001 and 4000x100)
```

**Comment by vinid** [comment]
Hello :)

One thing I'd like to clarify: the `text_for_bow` is optional only because the ZeroShotTM model does not need it for prediction, however, the CombinedTM does need it.

Since you want to deploy this you need to also store, somewhere, the `TopicModelDataPreparation` object. Because this is the one that is going to give you the dataset that is compatible with your representation.

So:

1) Train the model and save the model and the object that you instantiated with  `TopicModelDataPreparation`. You can use [pickle](https://wiki.python.org/moin/UsingPickle) for that.

2) At prediction time, you can create the dataset for prediction by first loading the `TopicModelDataPreparation` object, creating the test dataset with it, and then doing the predictions with the model.

Happy to be more precise if needed :)

**Comment by dmolina2** [comment]
Hey @vinid ! 
Thanks for your response and the aclaration about the `text_for_bow` attribute.
I will try what you propose and check how it goes.

Regards.
