### ISSUE TITLE
Support on Amazon Sagemaker

### ISSUE THREAD

**Issue by tomdulin** [MilaNLProc/contextualized-topic-models#60]
Attempting to test this package in amazon sagemaker on python3

### Description

Pip is failing to install module, getting module not found error.

### What I Did

```
!pip install contextualized_topic_models
import contextualized_topic_models
```

output:
Collecting contextualized_topic_models
  Using cached contextualized_topic_models-1.8.2-py2.py3-none-any.whl (29 kB)
Collecting gensim==3.8.3
  Using cached gensim-3.8.3-cp37-cp37m-manylinux1_x86_64.whl (24.2 MB)
Collecting scipy==1.4.1
  Using cached scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)
Collecting tqdm==4.56.0
  Using cached tqdm-4.56.0-py2.py3-none-any.whl (72 kB)
Requirement already satisfied: wordcloud==1.8.1 in /opt/conda/lib/python3.7/site-packages (from contextualized_topic_models) (1.8.1)
Collecting numpy==1.19.1
  Using cached numpy-1.19.1-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
Collecting sentence-transformers==0.4.1
  Using cached sentence-transformers-0.4.1.tar.gz (64 kB)
Collecting torchvision>=0.7.0
  Using cached torchvision-0.9.1-cp37-cp37m-manylinux1_x86_64.whl (17.4 MB)
Collecting torch>=1.6.0
  Downloading torch-1.8.1-cp37-cp37m-manylinux1_x86_64.whl (804.1 MB)
     |████████████████████████████████| 804.1 MB 77.5 MB/s eta 0:00:01    |███▋                            | 91.7 MB 75.8 MB/s eta 0:00:10     |████▎                           | 106.4 MB 75.8 MB/s eta 0:00:10     |███████▉                        | 195.9 MB 64.6 MB/s eta 0:00:10     |█████████▊                      | 244.1 MB 64.6 MB/s eta 0:00:09     |████████████▎                   | 308.5 MB 80.7 MB/s eta 0:00:07██████████████▉           | 522.5 MB 73.7 MB/s eta 0:00:04Killed
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-88f62e5c1b8e> in <module>
      1 get_ipython().system('pip install contextualized_topic_models')
----> 2 import contextualized_topic_models
      3 from contextualized_topic_models.utils.data_preparation import TopicModelDataPreparation
      4 from contextualized_topic_models.utils.data_preparation import bert_embeddings_from_file
      5 from contextualized_topic_models.datasets.dataset import CTMDataset

ModuleNotFoundError: No module named 'contextualized_topic_models'

**Comment by vinid** [comment]
Hi @tomdulin,

is there any more information in the traceback?

from what I can see, the problem is that the pip installation script is begin killed (`522.5 MB 73.7 MB/s eta 0:00:04Killed`) during the installation of torch.

Do you have any space/usage limits on amazon sagemaker that might prevent you from installing the package on sagemaker?
