### ISSUE TITLE
Contextized-topic-models weird gpu usage (pytorch and tensorflow working fine)

### ISSUE THREAD

**Issue by Yubel124** [MilaNLProc/contextualized-topic-models#62]
* Contextualized Topic Models version: 1.8.2
* Python version: 3.7.6
* Operating System: Windows 10 Pro

### Description

I'm trying to get Contextualized Topic Models tutorial to run on my gpu (rtx 3090).

### What I Did

At the very start of the .fit() I see a spike in gpu usage and gpu memory get allocated then gpu usage sits at just 2-4% with the model taking several minutes to train. I tried the same code on google colab and it ran in seconds. Additionally I see my cpu usage at nearly 100% during the entire run. The only explanation I have for this behavior is if the code is trying to run in float64 mode which would cripple the speed of a 3090; as I fairly certain my gpu drivers are installed correctly as I see normal gpu usage when using tensorflow, and pytorch is detecting my devices. Any help that could be offered would be much appreciated and please let me know if there is any more information that I could provide that would be helpful.

**Comment by vinid** [comment]
Hi @Yubel124!

This is weird, the 100% usage of the CPU seems to suggest that the model is not running on the GPU at all, but if torch detects the GPU there's no reason for the model to ignore it.

Let me run some tests. 

In the meantime, can you confirm that `torch.cuda.device_count()` returns 1? like, right before the `.fit()` method.

**Comment by Yubel124** [comment]
Yes I can confirm that torch.cuda.device_count() returns 1. Also torch.cuda.get_device_name(0) returns GeForce RTX 3090.

**Comment by Yubel124** [comment]
Also I can confirm that torch is using my gpu I ran a test model and saw a clear spike in gpu usage when the code was running. Hope that helps as well.

**Comment by Yubel124** [comment]
Just an update while I still have been unable to get it run on my gpu natively on windows I was able to get it to run on my gpu through wsl2 with gpu pass though. I don't know if that helps at all in tracking down this issue but I thought I would give an update.

**Comment by vinid** [comment]
Hi!

thanks a lot! 

I tried on Windows but I do not have the same GPU and thus I cannot replicate the issue entirely somehow.

Happy you found a solution, if you have any link you want to share it might be helpful for others with the same issue!
