### ISSUE TITLE
Contextualized Topic Model in Pyspark (Apache Spark Backend)

### ISSUE THREAD

**Issue by pyturn** [MilaNLProc/contextualized-topic-models#64]
Hi, 

Is there any implementation available for Contextual Topic Modeling in Pyspark (Apache Spark) Backend. If not, then what all functionalities needs to be changed to run it on Pyspark ? 

Thanks.

**Comment by vinid** [comment]
Hi @pyturn!

I am not sure about what would be needed to run the model on pyspark; what would be the use case you have in mind? If you use pyspark for the data loading part I still guess that the bottleneck would be the distributed training (something we still not support see this [issue](https://github.com/MilaNLProc/contextualized-topic-models/issues/6)).
