### ISSUE TITLE
Part of ctm.CTM._train_epoch running extremely slowly on local machine compared to google collab

### ISSUE THREAD

**Issue by Yubel124** [MilaNLProc/contextualized-topic-models#66]
* Contextualized Topic Models version: 1.8.2
* Python version: 3.7.6
* Operating System: Windows 10 Pro
* System info: 
  * GPU: RTX 3090
  * CPU: 5950x/9900k (upgraded CPU while testing no change in behavior)

### Background

~2 weeks ago I opened a ticket relating to low/no gpu usage when running the Contextualized Topic Models tutorial on my local machine #62. I thought the problem was that the code was not running on my gpu however I isolated the part of the code that is taking a large amount of time to run and it is in fact this single line of code in ctm.CTM()._train_epoch  "for batch_samples in loader:" (which I don't think this is running on the gpu). It seems that entering this for loop is taking anywhere from 2-10 seconds for some reason. 

### What I Did

I made this change to the base code to find this.  
```
starts = time.time()
for batch_samples in loader:
    print(f"top of loop {time.time()-starts}")
```
I made this change in 
```
ctm.CTM()._train_epoch 
```
The actual body of the for loop is taking milliseconds to run. But entering the loop for some reason is taking forever. I was wondering if this behavior was known or encountered before as this behavior doesn't occur on google collab and weirdly when running in wsl2 the time taken to execute this line is reduced (~5-10x faster) though not to the speed of google collab. I don't know if this is an actual issue or not but I thought that I should report my finds incase it is.

**Comment by Yubel124** [comment]
I found the problem I didn't see the line in the documentation that said set num_data_loader_workers=0 on windows. Sorry for the trouble.

**Comment by vinid** [comment]
No worries!

happy you have found a solution!
