### ISSUE TITLE
Covering other langauges

### ISSUE THREAD

**Issue by vinid** [MilaNLProc/contextualized-topic-models#71]
https://github.com/MilaNLProc/contextualized-topic-models/blob/4fdf8d922500bd2c24f8df068e0f3c898ad85451/contextualized_topic_models/utils/preprocessing.py#L35

Need to fix this to support other languages

**Comment by StrangeFate** [comment]
for korean,

vectorizer = CountVectorizer(max_features=self.vocabulary_size, token_pattern=r'\b[a-zA-Zㄱ-ㅎㅏ-ㅣ가-힣]{2,}\b')

worked in the tutorial for brief testing

**Comment by vinid** [comment]
Thanks!

**Comment by StrangeFate** [comment]
> Thanks!

Btw, is there a way to define the stop words as an list and use it? Since nltk doesnt support the korean stop words, for the korean language, it need some diffrent way to do it. I could change some code to do it but....😀

Thanks for the great work!

**Comment by StrangeFate** [comment]
> Check if [this](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/utils/preprocessing.py#L59) covers your usecase, otherwise I can try to adapt it to yours :)

Thanks! I will check it out and will leave some results here later 😀

**Comment by StrangeFate** [comment]
> Check if [this](https://github.com/MilaNLProc/contextualized-topic-models/blob/master/contextualized_topic_models/utils/preprocessing.py#L59) covers your usecase, otherwise I can try to adapt it to yours :)

I just checked it out and i think the stopwords function works. But the problem was found from another aspect. For Korean language, white space tokenization doesn't work since the structure of the language..LOL I guess i need to come up with some solution by myself. I will leave code when im done with it. Thanks for the help!
