### ISSUE TITLE
PyLda Visualization error

### ISSUE THREAD

**Issue by hnxue** [MilaNLProc/contextualized-topic-models#78]
* Contextualized Topic Models version: 2.0.1
* Python version: 3.6.9
* Operating System: MacOS

### Description

Hi, I copied the code of visualization, but it gave a type error (screenshot below). I'm not sure if it's a problem with pandas or pyLDAvis or my dataset. Feel free to take a look!
![image](https://user-images.githubusercontent.com/57650250/127637238-6ec29092-0bc3-42c0-9f27-f7439f55c884.png)

Many thanks!

**Comment by vinid** [comment]
Hello!

This is weird, I just tried locally and it worked.

Can you share the dataset with me?

**Comment by hnxue** [comment]
Sure! Please see attached. Thanks!
[posts.txt](https://github.com/MilaNLProc/contextualized-topic-models/files/6909432/posts.txt)

**Comment by vinid** [comment]
Hello @hnxue (very sorry for the late reply)

I was able to run CombinedTM on your dataset by cleaning the data a bit. 
Are you applying some pre-processing to the data? I wonder if links generate errors.

I have used our WhiteSpacePreprocessing utility to do a quick preprocessing (note that this does not remove links, just breaks them in whitespace chunks):

```python

from contextualized_topic_models.utils.preprocessing import WhiteSpacePreprocessing

documents = [line.strip() for line in open(text_file, encoding="utf-8").readlines()]
sp = WhiteSpacePreprocessing(documents, stopwords_language='english')
preprocessed_documents, unpreprocessed_corpus, vocab = sp.preprocess() ````

And after using this, I got the visualizations from pyLDA without issues.

Hope this helps

**Comment by hnxue** [comment]
Hi, I didn't apply any other processing and used the same code here, though it still shows error. I was able to run CTM as well; it's just the pyLDA with the same error above:

``` Python
documents = [line.strip() for line in open(file, encoding="utf-8").readlines()]
sp = WhiteSpacePreprocessing(documents, stopwords_language='english')
preprocessed_documents, unpreprocessed_corpus, vocab = sp.preprocess()

tp = TopicModelDataPreparation("paraphrase-distilroberta-base-v1")
training_dataset = tp.fit(text_for_contextual=unpreprocessed_corpus, text_for_bow=preprocessed_documents)

ctm = ZeroShotTM(bow_size=len(tp.vocab), contextual_size=768, n_components=4, num_epochs=7)
ctm.fit(training_dataset) # run the model

import pyLDAvis as vis
lda_vis_data = ctm.get_ldavis_data_format(tp.vocab, training_dataset, n_samples=20)
ctm_pd = vis.prepare(**lda_vis_data)
vis.display(ctm_pd)
```

Thanks!

**Comment by vinid** [comment]
Ok I was able to find the issue, the problem happens when the notebook is not restarted after the installation of both ctm and pyldavis (there is probably some mismatch in the versions of the dependencies that is solved with a restart).

If you run the two pip commands and then restart the notebook, you should be able to run pyldavis without problems:

See the picture:

![Screenshot from 2021-08-12 20-46-01](https://user-images.githubusercontent.com/2234699/129251621-b00c41fe-7292-4aab-85b9-7ea677c9806d.png)

Let me know if this helps :)

**Comment by hnxue** [comment]
It works now! Thank you so much!!!
