### ISSUE TITLE
RuntimeError in the Zero-Shot Cross-lingual Topic Modeling Colab tutorial

### ISSUE THREAD

**Issue by Herve07h22** [MilaNLProc/contextualized-topic-models#79]
* Contextualized Topic Models version: 2.0.1
* Python version: 3.7
* Operating System: Colab (runtime restarted, GPU mode)

### Description

When running Zero-Shot Cross-lingual Topic Modeling (Preproc+Viz) (stable v2.0.0) mentioned in the README (https://colab.research.google.com/drive/1bfWUYEypULFk_4Tfff-Pb_n7-tSjEe9v?usp=sharing), an error occurs at step 9 (running the model). 

RuntimeError: Function AddmmBackward returned an invalid gradient at index 2 - got [768, 100] but expected shape compatible with [512, 100]

### What I Did

```
ctm = ZeroShotTM(bow_size=len(tp.vocab), contextual_size=512, n_components=50, num_epochs=20)
ctm.fit(training_dataset) # run the model
```
<img width="1307" alt="Capture d’écran 2021-08-03 à 09 49 57" src="https://user-images.githubusercontent.com/37082968/127978911-562c3e88-d375-45a9-8fa7-964eeea418cc.png">

**Comment by vinid** [comment]
Hello @Herve07h22!

thanks for finding this!

when I changed the colab and added the new embedding model I forgot to update the line where I run ZeroShotTM

This should work:
```python

ctm = ZeroShotTM(bow_size=len(tp.vocab), contextual_size=768, n_components=50, num_epochs=20)
ctm.fit(training_dataset) # run the model

```
