### ISSUE TITLE
Runtime error when training Kitty with custom training data

### ISSUE THREAD

**Issue by carschno** [MilaNLProc/contextualized-topic-models#88]
* Contextualized Topic Models version: 2.2.0
* Python version: 3.7.12
* Operating System: Google Colab

### Description

I've been following the [Kitty tutorial](https://colab.research.google.com/drive/1ZO6y-laPMnIT6boMwNXK4WNiyAUWUK4L?usp=sharing#scrollTo=_V3256epBoZ9), and adapted it to use my own training data, read from a CSV file in my Google Drive which contains text data in the `title` column:

```
import csv
with open("/content/drive/MyDrive/mydata.csv") as f:
  reader = csv.DictReader(f)
  training = [line["title"].strip() for line in reader]
```
The training data size is 1270 entries, and there are no empty lines:
```
len(training)
1270

all(t for t in training)
True
```
Asserting that `training` is a list of strings:
```
type(training) 
list

all(type(t) == str for t in training)
True
```

### What I Did

So I run the [training cell](https://colab.research.google.com/drive/1ZO6y-laPMnIT6boMwNXK4WNiyAUWUK4L#scrollTo=H3ZfFaKdSXTE&line=1&uniqifier=1), unchanged from the tutorial with my own `training` data:
```
kt = Kitty()
kt.train(training, topics=5, embedding_model="paraphrase-distilroberta-base-v2", language="english")
```
It seems to process the batches fine, but then raises a RuntimeError:
```
Batches: 100%
7/7 [00:02<00:00, 3.18it/s]

0it [00:00, ?it/s]

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-22-8486cab2bc57> in <module>()
      1 kt = Kitty()
----> 2 kt.train(training, topics=5, embedding_model="paraphrase-distilroberta-base-v2", language="english")

3 frames

/usr/local/lib/python3.7/dist-packages/contextualized_topic_models/models/ctm.py in _loss(self, inputs, word_dists, prior_mean, prior_variance, posterior_mean, posterior_variance, posterior_log_variance)
    159 
    160         # Reconstruction term
--> 161         RL = -torch.sum(inputs * torch.log(word_dists + 1e-10), dim=1)
    162 
    163         #loss = self.weights["beta"]*KL + RL

RuntimeError: The size of tensor a (1989) must match the size of tensor b (2000) at non-singleton dimension 1
```
Are there any particular requirements on the training data in terms of size, content etc.?

Unfortunately, I cannot share my training data, but I am very much willing to check for other particularities.

**Comment by vinid** [comment]
Are you sure those are unique? Seems like you are getting just the tokens, I'd have done something like:

```python
tokens = {w for line in training for w in line.split() }
len(set(tokens))

```

-----


Kitty applies [this preprocessing](https://github.com/MilaNLProc/contextualized-topic-models/blob/1558afd807ea9df57334e20898e0fb76e33152da/contextualized_topic_models/utils/preprocessing.py#L6).

Can you run 

```python
from contextualized_topic_models.utils.preprocessing import WhiteSpacePreprocessing
sp = WhiteSpacePreprocessing(training, "english", 2000)
preprocessed_documents, unpreprocessed_documents, vocab = sp.preprocess()
words_unique = set([word for sentence in preprocessed_documents for word in sentence.split()])
```

and share with me the values of:

```python

len(vocab)
len(words_unique)

```

**Comment by carschno** [comment]
> Are you sure those are unique? Seems like you are getting just the tokens, I'd have done something like:

The extra conversion into a set is redundant, as I was already producing a set using a [set (not a list!) comprehension](https://docs.python.org/3/tutorial/datastructures.html#sets). Consequently, the number for `len(set(tokens))` is the same, still 5370.

However, after running the code you shared, I get these values:
```
len(vocab)
2000
```
and
```
len(words_unique)
1989
```
Given that 1989 and 2000 are the values referred in initial the RuntimeError message, this looks very much like the route to the root cause to me. I don't have enough internal insight to understand what exactly happens here.

I suspect that the difference between the unique words I had (5370) and in `words_unique` (1989) is (partly) due to the stopwords removal. I don't understand, however, if the issue is that there must be at least 2000 unique tokens, or if the problem lies somewhere else.
