### ISSUE TITLE
Training combined model on Databricks hangs 

### ISSUE THREAD

**Issue by GullyBurns** [MilaNLProc/contextualized-topic-models#90]
* Contextualized Topic Models version: 2.2.0
* Python version: Python 3.8.8
* Operating System: Linux 0728-045845-hah138-10-14-5-112 5.4.0-1055-aws 18.04.1-Ubuntu SMP  UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description

Trying to run the basic CTM demo for the combined TM from this CoLab notebook : https://colab.research.google.com/drive/1fXJjr_rwqvpp1IdNQ4dxqN4Dp88cxO97?usp=sharing#scrollTo=stAb2Q4eBB3W

> ctm = CombinedTM(bow_size=len(tp.vocab), contextual_size=768, n_components=50, num_epochs=20)
> ctm.fit(training_dataset) # run the model

### What I Did

This is the screenshot (from databricks) that has not changed for ~30 minutes.

![image](https://user-images.githubusercontent.com/45613102/137979971-132c3a45-3c38-405d-b2e0-b6866fc5417e.png)

Running this on the standard dbpedia set just hangs on a given specific epoch:  https://raw.githubusercontent.com/vinid/data/master/dbpedia_sample_abstract_20k_unprep.txt

I expected later epochs to take roughly the same amount of time as earlier ones and so when an epoch takes much longer, it seems to be a block rather than just the code taking a long time.

**Comment by GullyBurns** [comment]
Hey Federico, 

Our implementation is really firewalled so there's no way for you to tinker locally. Is there any way to set logging parameters in the source code to get some diagnostics. I can ask some of our local Databricks experts to take a look and see what might be going on. 

But the basic demo on the dbpedia data should build in a few minutes, right?

Gul

**Comment by tuulia** [comment]
Hello.
I had the same problem with the Databricks and the model stopped working randomly after some epochs. What worked for me was to change the number of workers on Dataloader to 0.  
Tuulia

**Comment by GullyBurns** [comment]
We just got confirmation from the Databricks folks about this as a solution.
